/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as ApiPiezinRouteImport } from './routes/api/piezin'
import { Route as AdminVideoconferencesRouteImport } from './routes/admin.videoconferences'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRouletteRouteImport } from './routes/admin.roulette'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin.enrollments'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiAdminResourceUploadRouteImport } from './routes/api/admin/resource-upload'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CursosRoute,
} as any)
const ApiPiezinRoute = ApiPiezinRouteImport.update({
  id: '/api/piezin',
  path: '/api/piezin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideoconferencesRoute = AdminVideoconferencesRouteImport.update({
  id: '/videoconferences',
  path: '/videoconferences',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRouletteRoute = AdminRouletteRouteImport.update({
  id: '/roulette',
  path: '/roulette',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminResourceUploadRoute = ApiAdminResourceUploadRouteImport.update({
  id: '/api/admin/resource-upload',
  path: '/api/admin/resource-upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cursos': typeof CursosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/roulette': typeof AdminRouletteRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videoconferences': typeof AdminVideoconferencesRoute
  '/api/piezin': typeof ApiPiezinRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/api/admin/resource-upload': typeof ApiAdminResourceUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cursos': typeof CursosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/roulette': typeof AdminRouletteRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videoconferences': typeof AdminVideoconferencesRoute
  '/api/piezin': typeof ApiPiezinRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/api/admin/resource-upload': typeof ApiAdminResourceUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cursos': typeof CursosRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/roulette': typeof AdminRouletteRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videoconferences': typeof AdminVideoconferencesRoute
  '/api/piezin': typeof ApiPiezinRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/api/admin/resource-upload': typeof ApiAdminResourceUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cursos'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/enrollments'
    | '/admin/roulette'
    | '/admin/users'
    | '/admin/videoconferences'
    | '/api/piezin'
    | '/cursos/$slug'
    | '/api/admin/resource-upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cursos'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/enrollments'
    | '/admin/roulette'
    | '/admin/users'
    | '/admin/videoconferences'
    | '/api/piezin'
    | '/cursos/$slug'
    | '/api/admin/resource-upload'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cursos'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/enrollments'
    | '/admin/roulette'
    | '/admin/users'
    | '/admin/videoconferences'
    | '/api/piezin'
    | '/cursos/$slug'
    | '/api/admin/resource-upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CursosRoute: typeof CursosRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPiezinRoute: typeof ApiPiezinRoute
  ApiAdminResourceUploadRoute: typeof ApiAdminResourceUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof CursosRoute
    }
    '/api/piezin': {
      id: '/api/piezin'
      path: '/api/piezin'
      fullPath: '/api/piezin'
      preLoaderRoute: typeof ApiPiezinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videoconferences': {
      id: '/admin/videoconferences'
      path: '/videoconferences'
      fullPath: '/admin/videoconferences'
      preLoaderRoute: typeof AdminVideoconferencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roulette': {
      id: '/admin/roulette'
      path: '/roulette'
      fullPath: '/admin/roulette'
      preLoaderRoute: typeof AdminRouletteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/resource-upload': {
      id: '/api/admin/resource-upload'
      path: '/api/admin/resource-upload'
      fullPath: '/api/admin/resource-upload'
      preLoaderRoute: typeof ApiAdminResourceUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminRouletteRoute: typeof AdminRouletteRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideoconferencesRoute: typeof AdminVideoconferencesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminRouletteRoute: AdminRouletteRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideoconferencesRoute: AdminVideoconferencesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CursosRouteChildren {
  CursosSlugRoute: typeof CursosSlugRoute
}

const CursosRouteChildren: CursosRouteChildren = {
  CursosSlugRoute: CursosSlugRoute,
}

const CursosRouteWithChildren =
  CursosRoute._addFileChildren(CursosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CursosRoute: CursosRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPiezinRoute: ApiPiezinRoute,
  ApiAdminResourceUploadRoute: ApiAdminResourceUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
